export const ADD_TODO = "ADD_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const RETURN_COMPLETED_TODO = "RETURN_COMPLETED_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const RESTORE_TODO = "RESTORE_TODO";

export const FETCH_TODOS = "FETCH_TODOS"
export const SET_FETCHED_TODOS = "SET_FETCHED_TODOS";